config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'sending#index'

  namespace :admin do
    mount Sidekiq::Web => '/sidekiq' # Sidekiq UI
  end

  post :send_mail, to: 'sending#send_mail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mailer_data.rb
class MailerData
  include ActiveModel::Model

  attr_accessor :name, :date_begin, :date_end, :email, :files

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :date_begin, :date_end, :email, presence: { message: 'Поле не может быть пустым' }
  validates :email, format: { with: VALID_EMAIL_REGEX, message: 'Неверный формат email' }

  validate :comparison_dates
  validate :check_files_quantity

  private

  def comparison_dates
    return false unless date_end.present? && date_begin.present?

    if date_end < date_begin
      errors.add('date_end', 'Дата окончания д. б. больше даты начала')
    end
  end

  def check_files_quantity
    unless files&.size.in?(1..5)
      errors.add('files', 'Кол-во загружаемых файлов д. б. от 1 до 5')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sending_controller.rb
class SendingController < ApplicationController
  def index; end
  
  def send_mail
    @data = MailerData.new(mailer_params)

    if @data.valid?
      ::Sending::UploadFile.(params[:mailer_data][:files]) if params[:mailer_data][:files].present?
      SomeMailer.new_email(
        params[:mailer_data][:name],
        params[:mailer_data][:date_begin],
        params[:mailer_data][:date_end],
        files_paths,
        params[:mailer_data][:email]
      ).deliver_later

      render :success
    end
  end

  private

  def mailer_params
    params.require(:mailer_data)
      .permit(:name, :date_begin, :date_end, :email, files: [])
  end

  def files_paths
    {}.tap do |items|
      params[:mailer_data][:files].each do |file|
        items[file.original_filename] = "#{request.base_url}/uploads/#{file.original_filename}"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleSender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sending/index.html.slim
html
  head
    title Форма отправки сообщения
    = stylesheet_link_tag :sending

  body
    h2.text-md-center.pt-5
      = 'Заполните поля формы'

    .container.col-md-3.text-md-center

      = form_for :mailer_data, url: send_mail_url, remote: true do |form|
        .form-group.d-flex.justify-content-between
          = form.label :name, 'Название', class: 'col-form-label col-sm-3 text-sm-left',for: 'name'
          = form.text_field :name, class: "form-control col-sm-9 #{'errors' if flash[:errors].present?}", placeholder: 'Введите название'

        .form-group.d-flex.justify-content-between
          = form.label :date_begin, 'Начало', class: 'col-form-label col-sm-3 text-sm-left', for: 'date_begin'
          = form.date_field :date_begin, class: 'form-control col-sm-9', placeholder: 'Введите дату начала'

        .form-group.d-flex.justify-content-between
          = form.label :date_end, 'Окончание', class: 'col-form-label col-sm-3 text-sm-left', for: 'date_end'
          = form.date_field :date_end, class: 'form-control col-sm-9', placeholder: 'Введите дату окончания'
        
        .form-group.d-flex.justify-content-between
          = form.label :files, 'Файлы', class: 'col-form-label col-sm-3 text-sm-left', for: 'files'
          = form.file_field :files, class: 'col-sm-9', multiple: true

        .form-group.d-flex.justify-content-between
          = form.label :email, 'Email', class: 'col-form-label col-sm-3 text-sm-left', for: 'email'
          = form.text_field :email, class: 'form-control col-sm-9', placeholder: 'Введите название'
        
        .form-group.row.justify-content-around
          = form.submit 'Отправить', class: 'btn btn-primary mb-2 btn-mr btn-width', style: 'width: 150px;', data: { disable_with: "Отправка..." }
          = form.button 'Очистить', class: 'btn btn-danger mb-2 btn-width', type: 'reset', style: 'width: 150px;'

app/views/sending/send_mail.js.erb
removeErrors();

var json = JSON.parse('<%= j @data.errors.messages.to_json.html_safe %>');
var prefix = 'mailer_data';

$.each(json, function(key, value) {
  var goal_field = $(`#${prefix}_${key}`);
  goal_field.addClass('error-field');
  classes = 'error-label text-md-left col-md-12 pt-1'
  $(goal_field.parent()).append(
    `<label class='${classes}'><span class='error-text'>${value[0]}</span></label>`
  );
});

$('button:reset').on('click', function() {
  removeErrors();
});

$('form').on('submit', function() {
  removeErrors();
})



function removeErrors() {
  $('.error-label').remove();
  $('.error-field').removeClass('error-field');
}

app/views/sending/success.js.erb
alert('Поздравдяем! Письмо отправлено на <%= j params[:mailer_data][:email] %>')